<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Models\AviatorRound;
use App\Models\GameSetting;
use Illuminate\Http\Request;
use Carbon\Carbon;

class AviatorRoundController extends Controller
{
    public function createRound(Request $request)
    {
        $request->validate([
            'crash_point' => 'required|numeric|min:1.00'
        ]);

        // Server-side enforcement of the admin minimum multiplier. The crash
        // point is generated by the client, so clamp it here as well so a
        // tampered request can never crash below the configured floor.
        $crashPoint = (float) $request->crash_point;
        $minMultiplier = (float) optional(
            GameSetting::where('game_key', 'aviator')->first()
        )->min_multiplier;
        if ($minMultiplier > 1.0 && $crashPoint < $minMultiplier) {
            $crashPoint = $minMultiplier;
        }

        $round = new AviatorRound();
        // $round->game_id = 1; // Column does not exist
        $round->round_number = (AviatorRound::max('round_number') ?? 0) + 1;
        $round->crash_point = $crashPoint;
        $round->status = 'waiting';
        $round->started_at = Carbon::now();
        $round->save();

        return response()->json([
            'status' => 'success',
            'game_id' => $round->id,
            'round_number' => $round->round_number
        ]);
    }

    public function endRound(Request $request)
    {
        $request->validate(['game_id' => 'required|integer']);
        $round = AviatorRound::find($request->game_id);
        if($round) {
            $round->status = 'completed';
            $round->save();
        }
        return response()->json(['status' => 'success']);
    }
}
